export type Language = "zh_CN" | "en_US" | "ru_RU";
export type ModView = "all" | "active";
export type SearchMode = "fuzzy" | "exact";

export interface ModRecord {
  id: string;
  packageName: string;
  path?: string;
  packageType?: string;
  displayName: string;
  author: string;
  version: string;
  source: "local" | "workshop";
  category: string;
  enabled: boolean;
  description: string;
  compatible: string;
  size?: number;
  modifiedMs?: number;
  iconUrl?: string;
  previewUrl?: string;
  mediaLoaded?: boolean;
  mediaAttempts?: number;
}

export interface Profile {
  id: string;
  name: string;
  company: string;
  location: "local" | "steam" | "cloud";
  modCount: number;
  folder?: string;
  writable?: boolean;
}

export interface SaveSlot {
  profileId: string;
  slotId: string;
  folder: string;
  gameSii: string;
  displayName: string;
  lastModifiedMs: number;
  profileLocation: "local" | "readonly";
}

export interface UiCopy {
  appTitle: string;
  modWorkspace: string;
  modPage: string;
  profilePage: string;
  profileOverview: string;
  profileDetails: string;
  profileActions: string;
  openModPage: string;
  profileFolder: string;
  profileStatus: string;
  profilePresetCount: (count: number) => string;
  profileSwitch: string;
  profileOpenManager: string;
  profileOpenMods: string;
  profileOpenSaves: string;
  profileOpenLocalization: string;
  profileOpenDiagnostics: string;
  profileOpenFolder: string;
  localizationBase: string;
  chooseLocalizationBase: string;
  startLocalization: string;
  scan: string;
  cancelScan: string;
  scanning: string;
  scanCancelled: string;
  scanSummary: (added: number, updated: number, removed: number, inspected: number) => string;
  unsavedConfirm: string;
  save: string;
  launch: string;
  profiles: string;
  categories: string;
  allMods: string;
  activeMods: string;
  searchPlaceholder: string;
  searchFuzzy: string;
  searchExact: string;
  enableAll: string;
  disableAll: string;
  invert: string;
  moveTop: string;
  moveUp: string;
  moveDown: string;
  moveBottom: string;
  presetPlaceholder: string;
  presetSelectPlaceholder: string;
  savePreset: string;
  loadPreset: string;
  noSelection: string;
  selectHint: string;
  sourceLocal: string;
  sourceWorkshop: string;
  openLocation: string;
  openWorkshop: string;
  source: string;
  name: string;
  package: string;
  priority: string;
  enabled: string;
  category: string;
  author: string;
  version: string;
  compatible: string;
  readOnly: string;
  localProfile: string;
  launchUnavailable: string;
  noMods: string;
  statusReady: string;
  statusDirty: string;
  statusCount: (active: number, total: number) => string;
  secondary: string;
  localization: string;
  diagnostics: string;
  saves: string;
  tools: string;
  saveCount: (count: number) => string;
  noSaves: string;
  saveSelectHint: string;
  saveSnapshot: string;
  money: string;
  experience: string;
  level: string;
  apply: string;
  saveReadOnly: string;
  saveUpdated: string;
  autosave: string;
  entriesSummary: (entries: number, cached: number, scanned: number) => string;
  issueSummary: (red: number, yellow: number) => string;
  noneFound: string;
}
